const transformMailData = ({ templateName, ...data }) => {
  switch (templateName) {
    case 'verifyEmail': {
      return `<!DOCTYPE html> <html> <head> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"/> <style type="text/css"> @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap'); </style> </head> <body> <section style=" max-width: 600px; margin: auto; background-color: rgb(247 247 243); display: flex; flex-direction: column; align-items: center; padding: 1rem; " > <center> <img id="webLogo" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1650791637/o5ltoqkojugeqxphyjcb.png" alt="webLogo" style=" width: 60px; height: 60px; margin: 1rem;"/> </center> <center> <img id="env" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1650804079/jvrrc296ko8u1nda9k4l.png" alt="env.svg" style="width: 300px; margin: 1rem;"/> </center> <center> <h1 style="font-size: 2.2rem; margin: 1rem; font-weight: 500;">Please Verify your mail</h1> </center> <center> <a href="https://oscorpgaming.com/verify?token=${data.data}" target="_blank" style="text-decoration: none" ><button style=" margin-bottom: 1rem; outline: none; border: none; font-size: 1rem; color: white; padding: 0.6rem 1.2rem; border-radius: 5px; cursor: pointer; background-color: #080929; font-family: 'Roboto', sans-serif; font-weight: 100; cursor: pointer; " > Click here to Verify </button></a > </center> </section> </body> <html>`;
    }
    case 'resetPassword': {
      return `<!DOCTYPE html> <html> <head> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"/> <style type="text/css"> @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap'); </style> </head> <body> <section style=" max-width: 600px; margin: auto; background-color: rgb(247 247 243); display: flex; flex-direction: column; align-items: center; padding: 1rem; " > <center> <img id="webLogo" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1650791637/o5ltoqkojugeqxphyjcb.png" alt="webLogo" style=" width: 60px; height: 60px; margin: 1rem;"/> </center> <center> <img id="env" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1651516278/mez4e2kmpi6oguif9geg.png" alt="env.svg" style="width: 300px; margin: 1rem;"/> </center> <center> <h1 style="font-size: 2.2rem; margin: 1rem; font-weight: 500;">Please Reset your password</h1> </center> <center> <a href="https://oscorpgaming.com/reset?token=${data.data}" target="_blank" style="text-decoration: none" ><button style=" margin-bottom: 1rem; outline: none; border: none; font-size: 1rem; color: white; padding: 0.6rem 1.2rem; border-radius: 5px; cursor: pointer; background-color: #080929; font-family: 'Roboto', sans-serif; font-weight: 100; cursor: pointer; " > Set new password </button></a > </center> </section> </body> <html>`;
    }
    case 'inviteToTeam': {
      return `<!DOCTYPE html> <html> <head> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"/> <style type="text/css"> @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap'); </style> </head> <body> <section style=" max-width: 600px; margin: auto; background-color: rgb(247 247 243); display: flex; flex-direction: column; align-items: center; padding: 1rem; " > <center> <img id="webLogo" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1650791637/o5ltoqkojugeqxphyjcb.png" alt="webLogo" style=" width: 60px; height: 60px; margin: 1rem;"/> </center> <center> <img id="env" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1651523058/a7cxqjfl0de5odjgtx6j.png" alt="env.svg" style="width: 300px; margin: 1rem;"/> </center> <center> <h4 style="font-size: 1.2rem; margin: 1rem; font-weight: 500; text-align: center;">You have been invited to join a team. Your code is</h4> </center> <center> <h1 style="font-size: 2.2rem; margin: 1rem; font-weight: 500; text-align: center;">${data.data}</h1> </center> <center> </center> <h4 style="font-size: 1.2rem; margin: 1rem; font-weight: 500; text-align: center;">Enter this code to join the team. </h4> </section> </body> <html>`;
    }
    case 'resetTeamCode': {
      return `<!DOCTYPE html> <html> <head> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"/> <style type="text/css"> @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap'); </style> </head> <body> <section style=" max-width: 600px; margin: auto; background-color: rgb(247 247 243); display: flex; flex-direction: column; align-items: center; padding: 1rem; " > <center> <img id="webLogo" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1650791637/o5ltoqkojugeqxphyjcb.png" alt="webLogo" style=" width: 60px; height: 60px; margin: 1rem;"/> </center> <center> <img id="env" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1651523058/a7cxqjfl0de5odjgtx6j.png" alt="env.svg" style="width: 300px; margin: 1rem;"/> </center> <center> <h4 style="font-size: 1.2rem; margin: 1rem; font-weight: 500; text-align: center;">Your team code has been reset. Please enter this code </h4> </center> <center> <h1 style="font-size: 2.2rem; margin: 1rem; font-weight: 500; text-align: center;">${data.data}</h1> </center> <center> </center> <h4 style="font-size: 1.2rem; margin: 1rem; font-weight: 500; text-align: center;">on join a team page. </h4> </section> </body> <html>`;
    }
    case 'subscribe': {
      return `<!DOCTYPE html> <html> <head> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"/> <style type="text/css"> @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap'); </style> </head> <body> <section style=" max-width: 600px; margin: auto; background-color: rgb(247 247 243); display: flex; flex-direction: column; align-items: center; padding: 1rem; " > <center> <img id="webLogo" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1650791637/o5ltoqkojugeqxphyjcb.png" alt="webLogo" style=" width: 60px; height: 60px; margin: 1rem;"/> </center> <center> <img id="env" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1651524814/rbrzwzntqnw3ffpo0byf.png" alt="env.svg" style="width: 300px; margin: 1rem;"/> </center> <center> <h1 style="font-size: 2.2rem; margin: 1rem; font-weight: 500"> Welcome to 3NOT3 community.</h1> </center> <center>  <h4 style="font-size: 1.2rem; margin: 1rem; font-weight: 500">Thanks for subscribing.</h4> </center>  </section> </body> <html>`;
    }
    case 'roominfo': {
      return `<!DOCTYPE html> <html> <head> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"/> <style type="text/css"> @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap'); </style> </head> <body> <section style=" max-width: 600px; margin: auto; background-color: rgb(247 247 243); display: flex; flex-direction: column; align-items: center; padding: 1rem; " > <center> <img id="webLogo" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1650791637/o5ltoqkojugeqxphyjcb.png" alt="webLogo" style=" width: 60px; height: 60px; margin: 1rem;"/> </center> <center> <img id="env" src="https://res.cloudinary.com/nakul-londhe/image/upload/v1651524814/rbrzwzntqnw3ffpo0byf.png" alt="env.svg" style="width: 300px; margin: 1rem;"/> </center> <center> <h1 style="font-size: 2.2rem; margin: 1rem; font-weight: 500"> Welcome to 3NOT3 community.</h1> </center> <center>  <h4 style="font-size: 1.2rem; margin: 1rem; font-weight: 500">Your Room Id is ${data.data.roomid} and password is ${data.data.password}</h4> </center>  </section> </body> <html>`;
    }
    default: {
      return 'No String';
    }
  }
};

module.exports = transformMailData;
